// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_season_1 = "CgkIut7Vjv8REAIQDw"; // <GPGSID>
        public const string achievement_level_10_clear = "CgkIut7Vjv8REAIQBg"; // <GPGSID>
        public const string achievement_gainbox_step2 = "CgkIut7Vjv8REAIQCg"; // <GPGSID>
        public const string achievement_stater = "CgkIut7Vjv8REAIQAQ"; // <GPGSID>
        public const string achievement_gainbox_step4 = "CgkIut7Vjv8REAIQDQ"; // <GPGSID>
        public const string achievement_gainbox_step1 = "CgkIut7Vjv8REAIQCA"; // <GPGSID>
        public const string achievement_playcount = "CgkIut7Vjv8REAIQCw"; // <GPGSID>
        public const string achievement_level1_clear = "CgkIut7Vjv8REAIQAg"; // <GPGSID>
        public const string leaderboard_sumsumzombie_leaderboard = "CgkIut7Vjv8REAIQDg"; // <GPGSID>
        public const string achievement_level5_clear = "CgkIut7Vjv8REAIQBA"; // <GPGSID>
        public const string achievement_level2_clear = "CgkIut7Vjv8REAIQAw"; // <GPGSID>
        public const string achievement_level_7_clear = "CgkIut7Vjv8REAIQBQ"; // <GPGSID>
        public const string achievement_gainbox_step3 = "CgkIut7Vjv8REAIQDA"; // <GPGSID>
        public const string achievement_playtime = "CgkIut7Vjv8REAIQCQ"; // <GPGSID>
        public const string achievement_potion = "CgkIut7Vjv8REAIQBw"; // <GPGSID>

}

